/**
 * IEEE Volunteer Connect — Application Constants
 */

// ─── SUPER ADMIN ────────────────────────────────────────────
// Only this email gets SUPER_ADMIN privileges (global access to all colleges, 
// delete users, reset leaderboard, manage sub-admins).
export const SUPER_ADMIN_EMAIL = 'hussainkmajmal786@gmail.com';

// ─── ROLE DEFINITIONS ───────────────────────────────────────
export const ROLES = {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',          // Sub-admin — college-level access
    VOLUNTEER: 'VOLUNTEER',
    STUDENT: 'STUDENT',
};

// Helper to check if a role has admin-level access
export const isAdminRole = (role) => role === ROLES.SUPER_ADMIN || role === ROLES.ADMIN;

// ─── COLLEGE BRANCHES ───────────────────────────────────────
// Comprehensive catalog of Kerala engineering colleges and major
// institutions. Populates a <datalist> — users can also type a
// custom value if their college isn't listed.
// Sorted alphabetically within each section.
export const COLLEGE_BRANCHES = [
    // ─── National Institutes / Central / Deemed Universities ───
    'IIM Kozhikode',
    'IIIT Kottayam',
    'IIITM-K — Indian Institute of Information Technology & Management Kerala',
    'IIST — Indian Institute of Space Science and Technology Trivandrum',
    'NIT Calicut',
    'Amrita Vishwa Vidyapeetham — Amritapuri',
    'Cochin University of Science and Technology (CUSAT)',
    'Kerala University of Digital Sciences, Innovation and Technology',

    // ─── Government Engineering Colleges ───
    'College of Engineering Adoor',
    'College of Engineering Attingal',
    'College of Engineering Cherthala',
    'College of Engineering Chengannur',
    'College of Engineering Kallooppara',
    'College of Engineering Karunagappally',
    'College of Engineering Kidangoor (CEK)',
    'College of Engineering Kottarakkara',
    'College of Engineering Munnar',
    'College of Engineering Muttathara',
    'College of Engineering Pathanapuram',
    'College of Engineering Perumon',
    'College of Engineering Poonjar',
    'College of Engineering Thalassery',
    'College of Engineering Trikaripur',
    'College of Engineering Trivandrum (CET)',
    'College of Engineering Vadakara',
    'Govt Engineering College Barton Hill, Trivandrum',
    'Govt Engineering College Idukki',
    'Govt Engineering College Kannur',
    'Govt Engineering College Kozhikode',
    'Govt Engineering College Painavu',
    'Govt Engineering College Palakkad',
    'Govt Engineering College Sreekrishnapuram',
    'Govt Engineering College Thrissur',
    'Govt Engineering College Wayanad',
    'LBS College of Engineering, Kasaragod',
    'LBS Institute of Technology for Women, Trivandrum',
    'Model Engineering College, Thrikkakara (MEC)',
    'Rajiv Gandhi Institute of Technology, Kottayam (RIT)',

    // ─── Aided Engineering Colleges ───
    'Mar Athanasius College of Engineering, Kothamangalam (MACE)',
    'MES College of Engineering, Kuttippuram',
    'NSS College of Engineering, Palakkad',
    'TKM College of Engineering, Kollam',

    // ─── Self-financing Engineering Colleges ───
    'Adi Shankara Institute of Engineering and Technology, Kalady',
    'AKG College of Engineering and Technology, Kasaragod',
    'Al-Ameen Engineering College, Shoranur',
    'Al-Azhar College of Engineering and Technology, Thodupuzha',
    'Albertian Institute of Science and Technology, Kochi',
    'Amal Jyothi College of Engineering, Kanjirappally',
    'Ammini College of Engineering, Palakkad',
    'Archana College of Engineering, Pathanamthitta',
    'Awh Engineering College, Kozhikode',
    'Baselios Mathews II College of Engineering, Kollam',
    'Baselios Poulose II Catholicos College of Engineering, Piravom',
    'Caarmel Engineering College, Pathanamthitta',
    'Calicut University Institute of Engineering and Technology, Tenhipalam',
    'Carmel College of Engineering and Technology, Punnapra',
    'Christ Knowledge City, Muvattupuzha',
    'Christ College of Engineering, Irinjalakuda',
    'College of Engineering and Management, Punnapra',
    'College of Engineering, Aranmula',
    'College of Engineering, Karunagappally',
    'College of Engineering, Kidangoor',
    'College of Engineering, Pathanapuram',
    'College of Engineering, Perumon',
    'College of Engineering, Vadakara',
    'EKC Group of Institutions, Kothamangalam',
    'Federal Institute of Science and Technology, Angamaly (FISAT)',
    'Govt RIT, Velloor Pampady',
    'Heera College of Engineering and Technology, Trivandrum',
    'Holy Grace Academy of Engineering, Mala',
    'Holy Kings College of Engineering and Technology, Muvattupuzha',
    'ICCS College of Engineering and Management, Mannar',
    'Ilahia College of Engineering and Technology, Muvattupuzha',
    'Indira Gandhi Institute of Engineering and Technology, Nellikuzhi',
    'Jai Bharath College of Management and Engineering Technology, Perumbavoor',
    'Jawaharlal College of Engineering and Technology, Palakkad',
    'John Cox Memorial CSI Institute of Technology, Trivandrum',
    'Jyothi Engineering College, Cheruthuruthy',
    'KMCT College of Engineering, Kozhikode',
    'KMCT College of Engineering for Women, Kozhikode',
    'KMEA Engineering College, Aluva',
    'KMP College of Engineering, Perumbavoor',
    'KVM College of Engineering and Information Technology, Cherthala',
    'Lourdes Matha College of Science and Technology, Trivandrum',
    'Malabar College of Engineering and Technology, Thrissur',
    'Malabar Institute of Technology, Kannur',
    'Mangalam College of Engineering, Ettumanoor',
    'Mar Athanasius College of Engineering, Kothamangalam',
    'Mar Baselios Christian College of Engineering and Technology, Peermade',
    'Mar Baselios College of Engineering and Technology, Trivandrum (MBCET)',
    'Mar Baselios Institute of Technology and Science, Nellimattom (MBITS)',
    'Marian Engineering College, Trivandrum',
    'Mahatma Gandhi College of Engineering and Technology',
    'Mohandas College of Engineering and Technology, Trivandrum',
    'Mookambika Technical Campus, Idukki',
    'Mount Zion College of Engineering, Pathanamthitta',
    'Musaliar College of Engineering, Pathanamthitta',
    'Musaliar College of Engineering and Technology, Pathanamthitta',
    'Muthoot Institute of Technology and Science, Varikoli',
    'Nehru College of Engineering and Research Centre, Pampady',
    'Nirmala College of Engineering, Chalakudy',
    'Pinnacle School of Engineering and Technology, Anchal',
    'PRS College of Engineering and Technology, Trivandrum',
    'Rajadhani Institute of Engineering and Technology, Trivandrum',
    'Rajagiri School of Engineering & Technology, Kakkanad',
    'Rajiv Gandhi Institute of Technology, Velloor',
    'Royal College of Engineering and Technology, Thrissur',
    'Sadguru Swamy Nityananda Institute of Technology, Kanhangad',
    'Sahrdaya College of Engineering and Technology, Kodakara',
    'Saintgits College of Engineering, Kottayam',
    'Sarabhai Institute of Science and Technology, Trivandrum',
    'SCMS School of Engineering and Technology, Karukutty',
    'Shahul Hameed Memorial Engineering College, Kadakkal',
    'Sherwood College of Engineering Research and Technology',
    'Sivaji College of Engineering and Technology, Manivila',
    'Sree Buddha College of Engineering, Pattoor',
    'Sree Chitra Thirunal College of Engineering, Trivandrum (SCT)',
    'Sree Narayana Gurukulam College of Engineering, Kadayiruppu',
    'Sree Narayana Institute of Technology, Adoor',
    'Sreepathy Institute of Management and Technology, Vavanoor',
    'St. Joseph College of Engineering and Technology, Palai (SJCET)',
    'St. Thomas College of Engineering and Technology, Kannur',
    'Thejus Engineering College, Vellarakkad',
    'Thiagarajar Polytechnic College, Salem',
    'Toc H Institute of Science and Technology, Arakkunnam',
    'Travancore Engineering College, Kollam',
    'Trinity College of Engineering, Trivandrum',
    'UKF College of Engineering and Technology, Parippally',
    'Universal Engineering College, Vallivattom',
    'Valia Koonambaikulathamma College of Engineering and Technology, Parippally',
    'Vidya Academy of Science and Technology, Thrissur',
    'Vidya Academy of Science and Technology Technical Campus, Kilimanoor',
    'Vimal Jyothi Engineering College, Chemperi',
    'Viswajyothi College of Engineering and Technology, Vazhakulam',
    'YCT — Younus College of Engineering and Technology, Kollam',
    'Younus Institute of Technology, Vadakkevila',

    // ─── Other / Not Listed ───
    'Other (Type your college name)',
];
